### ISSUE TITLE
[Bug]: GitHub packages are not available to the public

### ISSUE THREAD

**Issue by asror1** [formfunction-hq/formfunction-monorepo#3]
Hello @arcticmatt, in the mono-repo you are using *private* GitHub packages which are not available for the *public* to download with `yarn/npm`, this is the error I get... 
```shell
error An unexpected error occurred: "https://npm.pkg.github.com/download/@formfunction-hq/formfunction-auction-house/0.0.5-alpha.146/67b0560416eebeca694ad724125fb26e73af935e: Request failed "401 Unauthorized"".
``` 
Is there a reason why you kept those GH packages *private*? And if so, could you add the necessary steps needed, to use those required dependencies.

**Comment by arcticmatt** [comment]
@asror1 I've just made all the packages public, although if you'd like to modify or add functionality to any of the SDKs, I recommend publishing the SDKs yourself by following the instructions in the READMEs

**Comment by asror1** [comment]
Sounds great, Thank you Matt!
